language: csharp
mono: none
dotnet: 5.0
solution: HW_4_Task_2.sln

script:
  - dotnet publish --configuration Release --runtime win-x64 /p:PublishSingleFile=true --outpute win-64

deploy:
  provider: releases
  apy_key: $.NET Core